name: "Publish to Docker registry"
description: "Publish an image/tags to a Docker registry"
inputs:
  registry:
    description: "Docker registry hostname"
    required: false
    default: "ghcr.io"
  username:
    description: "Docker registry account username"
    required: true
  password:
    description: "Docker registry account password"
    required: true
  image_name:
    description: "Docker image name"
    required: true
  branch:
    description: "Repository branch this image is built from"
    required: true
  commit_sha:
    description: "SHA hash of the commit that triggered this publish"
    required: true
  cuda_version:
    description: "CUDA version number to build for"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Convert image_name to lowercase
      id: lowercase_image_name
      shell: bash
      run: |
        echo "LOWERCASE_IMAGE_NAME=${{ inputs.image_name_input | lower }}" >> "$GITHUB_OUTPUT"
      env:
        image_name_input: ${{ inputs.image_name }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ steps.lowercase_image_name.outputs.LOWERCASE_IMAGE_NAME }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        file: Dockerfile
        tags: |
          ${{ inputs.registry }}/${{ steps.lowercase_image_name.outputs.LOWERCASE_IMAGE_NAME }}:cuda${{ inputs.cuda_version }}-latest-${{ inputs.branch }}
          ${{ inputs.registry }}/${{ steps.lowercase_image_name.outputs.LOWERCASE_IMAGE_NAME }}:cuda${{ inputs.cuda_version }}-${{ inputs.commit_sha }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          CUDA_VERSION=${{ inputs.cuda_version }}