name: Publish images to GHCR
on:
  push:
    branches:
      - "develop"
      - "main"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        cuda-version: ["12.4.1", "12.6.3", "12.8.1"]
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 50000
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish image
        uses: ./.github/actions/docker-publish-action
        with:
          branch: ${{ github.ref_name }}
          commit_sha: ${{ github.sha }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image_name: colinurbs/fp-studio
          cuda_version: ${{ matrix.cuda-version }}
