name: Publish images to GHCR
on:
  push:
    branches:
      - "develop"
      - "main"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        cuda-version: ["12.9", "12.8", "12.4"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Clean up unneeded tooling
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf /usr/local/share/boost
          rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Publish image
        uses: ./.github/actions/docker-publish-action
        with:
          branch: ${{ github.ref_name }}
          commit_sha: ${{ github.sha }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image_name: fp-studio
          cuda_version: ${{ matrix.cuda-version }}
  cleanup:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: read
      packages: write
    steps:
      - uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          container: ${{ github.repository }}
          dry-run: false
          prune-untagged: true
