name: Publish images to GHCR
on:
  push:
    branches:
      - "develop"
      - "main"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        cuda-version: ["12.9", "12.8", "12.4"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Clean up unneeded tooling
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf /usr/local/share/boost
          rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Publish image
        uses: ./.github/actions/docker-publish-action
        with:
          branch: ${{ github.ref_name }}
          commit_sha: ${{ github.sha }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image_name: ${{ github.repository_owner }}/fp-studio
          cuda_version: ${{ matrix.cuda-version }}
